# Generated by Django 5.2.8 on 2025-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_site', models.CharField(max_length=200, verbose_name='Nome do Site/Empresa')),
                ('logo_do_site', models.ImageField(blank=True, null=True, upload_to='institucional/logos/', verbose_name='Logo (Opcional)')),
                ('texto_chamada', models.TextField(help_text='Exibido em destaque no topo.', verbose_name='Texto de Chamada da Página Inicial')),
                ('texto_sobre', models.TextField(verbose_name='Texto Sobre a Empresa/Site')),
                ('imagem_sobre', models.ImageField(upload_to='institucional/sobre/', verbose_name='Imagem Sobre (Exibida ao lado do texto)')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Físico')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail de Contato')),
                ('whatsapp', models.CharField(help_text='Ex: +55 (11) 98765-4321', max_length=20, verbose_name='WhatsApp para Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Institucional',
                'verbose_name_plural': 'Página Institucional',
            },
        ),
    ]
