# Generated by Django 5.2.8 on 2025-11-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='maps_embed',
            field=models.TextField(blank=True, help_text='Cole aqui o código iframe de embed do Google Maps (opcional).', null=True, verbose_name='Embed do Google Maps'),
        ),
    ]
