# Generated by Django 5.2.8 on 2025-11-21 23:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Título / Nome do Item')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque Disponível')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Item')),
                ('foto', models.ImageField(upload_to='catalogo/itens/', verbose_name='Capa / Foto do Item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Catálogo',
                'verbose_name_plural': 'Itens do Catálogo',
                'ordering': ['nome'],
            },
        ),
    ]
